version: '3.8'
services:

  auth-service:
    environment:
      SECURED_USER_PASSWORD_HASH: $$argon2id$$v=19$$m=4096,t=192,p=2$$OJW5Ql4eXIkbWhsuuc74Vk56zCLq3MEuTeiFSeKbozY$$0vXHoA71GZLmhTJOwbXZtpPrWDWpH8Vv5OjUKLRuAQY
