version: '3.8'
services:

  # Planets service
  planets-service:
    image: kudryashovroman/graphql-federation-rust:planets-service
    depends_on:
      - planets-db
    environment:
      DATABASE_URL: postgres://postgres:$PLANETS_DB_PASSWORD@planets-db/planets
    restart: always
  planets-db:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: planets
      POSTGRES_PASSWORD: $PLANETS_DB_PASSWORD
    restart: always

  # Satellites service
  satellites-service:
    image: kudryashovroman/graphql-federation-rust:satellites-service
    depends_on:
      - satellites-db
    environment:
      DATABASE_URL: postgres://postgres:$SATELLITES_DB_PASSWORD@satellites-db/satellites
      SECRET_KEY: $SECRET_KEY
    restart: always
  satellites-db:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: satellites
      POSTGRES_PASSWORD: $SATELLITES_DB_PASSWORD
    restart: always

  # Auth service
  auth-service:
    image: kudryashovroman/graphql-federation-rust:auth-service
    depends_on:
      - users-db
    environment:
      DATABASE_URL: postgres://postgres:USERS_DB_PASSWORD@users-db/users
      SECRET_KEY: $SECRET_KEY
    restart: always
  users-db:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: users
      POSTGRES_PASSWORD: USERS_DB_PASSWORD
    restart: always

  # Apollo server
  apollo-server:
    image: kudryashovroman/graphql-federation-rust:apollo-server
    depends_on:
      - planets-service
      - satellites-service
      - auth-service
    ports:
      - 4000:4000
    environment:
      NODE_ENV: docker
    restart: always
