[package]
name = "planets-service"
version = "0.1.0"
edition = "2018"

[dependencies]
async-graphql = "1.16.11"
async-graphql-actix-web = "1.16.10"
actix-web = "2.0.0"
actix-rt = "1.1.1"
actix-web-actors = "2.0.0"
dataloader = "0.12"
futures = "0.3.5"
async-trait = "0.1.36"
num-bigint = { version = "0.2.6", features = ["serde"] }
bigdecimal = { version = "0.1.2", features = ["serde"] }
num = "0.3.0"
serde = { version = "1.0.114", features = ["derive"] }
diesel = { version = "1.4.5", features = ["postgres", "r2d2", "numeric"] }
diesel_migrations = "1.4.0"
dotenv = "0.15.0"
strum = "0.18.0"
strum_macros = "0.18.0"

[dev-dependencies]
serde_json = "1.0.56"
jsonpath_lib = "0.2.5"
