[package]
name = "planets-service"
version = "0.1.0"
edition = "2018"

[dependencies]
async-graphql = "2.1.5"
async-graphql-actix-web = "2.1.5"
actix-web = "3.3.0"
actix-rt = "1.1.1"
actix-web-actors = "3.0.0"
dataloader = "0.13.1"
futures = "0.3.8"
async-trait = "0.1.41"
bigdecimal = { version = "0.1.2", features = ["serde"] }
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"
diesel = { version = "1.4.5", features = ["postgres", "r2d2", "numeric"] }
diesel_migrations = "1.4.0"
dotenv = "0.15.0"
strum = "0.19.5"
strum_macros = "0.19.4"
rdkafka = { version = "0.24.0", features = ["cmake-build"] }
async-stream = "0.3.0"
lazy_static = "1.4.0"
jsonwebtoken = "7.2.0"

[dev-dependencies]
jsonpath_lib = "0.2.5"
testcontainers = "0.9.1"
