[package]
name = "planets-service"
version = "0.1.0"
edition = "2018"

[dependencies]
async-graphql = "1.14.2"
async-graphql-actix-web = "1.14.0"
actix-web = "2.0.0"
actix-rt = "1.1.1"
rust_decimal = { version = "1.5.0", features = ["serde-float"] }
num-bigint = { version = "0.2.6", features = ["serde"] }
bigdecimal = { version = "0.0.15", features = ["serde"] }
num = "0.2.1"
serde = { version = "1.0.110", features = ["derive"] }
diesel = { version = "1.4.4", features = ["postgres", "r2d2", "numeric"] }
diesel_migrations = "1.4.0"
dotenv = "0.15.0"
strum = "0.18.0"
strum_macros = "0.18.0"
