[package]
name = "satellites-service"
version = "0.1.0"
edition = "2018"

[dependencies]
async-graphql = "1.14.2"
async-graphql-actix-web = "1.14.0"
actix-web = "2.0.0"
actix-rt = "1.1.1"
serde = { version = "1.0.110", features = ["derive"] }
chrono = { version = "0.4.11", features = ["serde"] }
diesel = { version = "1.4.4", features = ["postgres", "r2d2", "chrono"] }
diesel_migrations = "1.4.0"
dotenv = "0.15.0"
strum = "0.18.0"
strum_macros = "0.18.0"
