[package]
name = "satellites-service"
version = "0.1.0"
edition = "2018"

[dependencies]
async-graphql = "1.17.0"
async-graphql-actix-web = "1.17.0"
actix-web = "2.0.0"
actix-rt = "1.1.1"
serde = { version = "1.0.114", features = ["derive"] }
diesel = { version = "1.4.5", features = ["postgres", "r2d2", "chrono"] }
diesel_migrations = "1.4.0"
chrono = { version = "0.4.15", features = ["serde"] }
dotenv = "0.15.0"
jsonwebtoken = "7.2.0"
lazy_static = "1.4.0"
strum = "0.19.2"
strum_macros = "0.19.2"
async-trait = "0.1.38"

[dev-dependencies]
serde_json = "1.0.56"
jsonpath_lib = "0.2.5"
testcontainers = "0.10.0"
