[package]
name = "satellites-service"
version = "0.1.0"
edition = "2018"

[dependencies]
async-graphql = "2.1.5"
async-graphql-actix-web = "2.1.5"
actix-web = "3.3.0"
actix-rt = "1.1.1"
serde = { version = "1.0.117", features = ["derive"] }
diesel = { version = "1.4.5", features = ["postgres", "r2d2", "chrono"] }
diesel_migrations = "1.4.0"
chrono = { version = "0.4.19", features = ["serde"] }
dotenv = "0.15.0"
strum = "0.19.5"
strum_macros = "0.19.4"

[dev-dependencies]
serde_json = "1.0.59"
jsonpath_lib = "0.2.5"
testcontainers = "0.9.1"
