[package]
name = "satellites-service"
version = "0.1.0"
edition = "2018"

[dependencies]
async-graphql = "=1.12.18"
async-graphql-actix-web = "=1.4.18"
actix-web = "2.0.0"
actix-rt = "1.1.1"
serde = { version = "1.0.110", features = ["derive"] }
chrono = { version = "0.4.11", features = ["serde"] }
diesel = { version = "1.4.4", features = ["postgres", "r2d2", "chrono"] }
diesel_migrations = "1.4.0"
dotenv = "0.15.0"
