[package]
name = "auth-service"
version = "0.1.0"
edition = "2018"

[dependencies]
async-graphql = "2.0.11"
async-graphql-actix-web = "2.0.11"
actix-web = "3.2.0"
actix-rt = "1.1.1"
serde = { version = "1.0.114", features = ["derive"] }
diesel = { version = "1.4.5", features = ["postgres", "r2d2", "chrono"] }
diesel_migrations = "1.4.0"
chrono = { version = "0.4.15", features = ["serde"] }
dotenv = "0.15.0"
argonautica = "0.2.0"
jsonwebtoken = "7.2.0"
lazy_static = "1.4.0"

[dev-dependencies]
serde_json = "1.0.56"
jsonpath_lib = "0.2.5"
base64 = "0.12.3"
testcontainers = "0.9.1"
