[package]
name = "auth-service"
version = "0.1.0"
authors = ["Roman Kudryashov <rskudryashov@gmail.com>"]
edition = "2018"

[dependencies]
common-utils = { path = "../common-utils" }
async-graphql = "2.1.7"
async-graphql-actix-web = "2.1.7"
actix-web = "3.3.2"
actix-rt = "1.1.1"
serde = { version = "1.0.117", features = ["derive"] }
diesel = { version = "1.4.5", features = ["postgres", "r2d2"] }
diesel_migrations = "1.4.0"
dotenv = "0.15.0"
argonautica = "0.2.0"
lazy_static = "1.4.0"
strum = "0.20.0"
strum_macros = "0.20.1"

[dev-dependencies]
serde_json = "1.0.60"
jsonpath_lib = "0.2.5"
base64 = "0.13.0"
testcontainers = "0.9.1"
