name: GraphQL Federation Rust build

on:
#  push:
#    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  apollo-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: kudryashovroman/graphql-federation-rust
          path: ./apollo-server
          tags: apollo-server
          push: ${{ github.event_name == 'push' }}
  auth-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: kudryashovroman/graphql-federation-rust
          path: ./auth-service
          tags: auth-service
          push: ${{ github.event_name == 'push' }}
  planets-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: kudryashovroman/graphql-federation-rust
          path: ./planets-service
          tags: planets-service
          push: ${{ github.event_name == 'push' }}
  satellites-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: kudryashovroman/graphql-federation-rust
          path: ./satellites-service
          tags: satellites-service
          push: ${{ github.event_name == 'push' }}
