name: GraphQL Federation build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:

  apollo-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: kudryashovroman/graphql-federation-rust
          path: ./apollo-server
          tags: apollo-server
          push: ${{ github.event_name == 'push' }}

  # todo maybe run tests inside docker container (change Dockerfile for that). Now it is not supported by testcontainers (https://github.com/testcontainers/testcontainers-rs/issues/129)
  test-rust-services:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test

  auth-service-image:
    needs: test-rust-services
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: kudryashovroman/graphql-federation-rust
          path: ./auth-service
          tags: auth-service
          push: ${{ github.event_name == 'push' }}

  planets-service-image:
    needs: test-rust-services
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: kudryashovroman/graphql-federation-rust
          path: ./planets-service
          tags: planets-service
          push: ${{ github.event_name == 'push' }}

  satellites-service-image:
    needs: test-rust-services
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: kudryashovroman/graphql-federation-rust
          path: ./satellites-service
          tags: satellites-service
          push: ${{ github.event_name == 'push' }}
